### ISSUE TITLE
Admin - Add Intake

### ISSUE THREAD

**Issue by MarsRomer2** [bcgov/CONN-CCBC-portal#1122]
As an administrator
I want to be able to add an intake into the future
So that I can directly control when intakes open and close

# Acceptance Criteria:

## Page: View Intakes dates
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/80f3eae9-8f09-40a9-b6ac-0c4bb5dbacab)

### Fields and info
- [x] "Add Intake" button
  
### Button Behaviour
- [x] **Visible when there is no future intake already (Future intake = start date > current date).**  
  _i.e. It can only have one intake in the future - one more than the current open intake.  
  If no intake is currently open, they can still only have one intake in the future. Once the intake opens, then they are allowed to add another intake into the future._
- [x] Hide "Add Intake" button
- [x] **Transition:** slide down - similar to: https://codepen.io/mbxtr/pen/OJPOYg

## Page: Add Intake
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/45e2852e-2543-4110-bd3b-7bc1a17d4469)

### Fields
- Intake # (Autogenerated) 
- Start Date
- End Date 
- Description (optional)
#
- [x] **Show next Intake number ** Gapless, sequential even if intake is soft-deleted
#
- [x] **Date and time are Pacific Timezone (PT)**
 (ensure this accounts for daylight savings time when necessary)

### Validations
- [x] Live validations on dates being correct
- [x] When pressing Save validate that the two dates are filled in
#
- **Required fields:**
- [x] Start date = null
Error message:  "Start date and time must be entered"
- [x] End date = null
Error message:  "End date and time must be entered"
#
- **Error state design:**
- [x] Field outlined red
- [x] Red warning text appears below each field
- [x] "Description (optional)" 
- [x] Description field - 150 characters
#
- [x] Scenario: Start date & Time > End Date from the 'last in the future' existent intake. 

- [x] The intake period cannot overlap with other existent intakes.
The `Start Date` must be `greater than` the `End Date from the chronologically previous intake`.
I.e. two intakes cannot be open at the same time.
Error message: "Start date & time must not overlap with other intakes"
#

- [x] Start date & time > current date and time
Error message: "Start date & time must be after current date & time"
- [x] End date & time > start date and time
Error message: "End date & time must be after start date & time"
#

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/2f5d9eaf-1e99-4632-96b9-9bce4e627003)

### Actions

- **Scenario: new intake saved**
Given all fields have valid information
When I click on Save
- [x] Then a new register with the inputs will be saved in the database
- [x] And the input fields will be reseted
- [x] And the form will disappear (transition: slide up)
- [x] And the new intake will appear in the list of intakes
- [x] And hide the "Add Intake" button 

- [x] On pressing cancel, form slides up, "add intake" button slides down. Data in the form is cleared.

## Not included:
- .

## Ultra Refinement 
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
@marcellmueller @VB-at-Bis @AntBush  @pbolduc 
Can you estimate how much extra effort would it be to do live validations on this instead 'on save'

**Comment by pbolduc** [comment]
@MarsRomer sorry, I do not work on this project so I am unable to provide guidance on the effort.

**Comment by VB-at-Bis** [comment]
"Live" validation means "on blur" event, right? .. meaning when the focus leave Start Date or End Date control?

**Comment by MarsRomer** [comment]
could be on blur, but perhaps even better is that as soon as they choose dates (what's the technical term for this)?
e.g. they choose end date in the past - as soon as they pick the date in the calendar it validates and provides feedback
e.g. they choose end date correctly, but then they choose start date to be AFTER the end-date which is not allowed, so as soon as they pick the start date in the calendar it validates and provides feedback

**Comment by VB-at-Bis** [comment]
Thanks for clarification! I added my estimate on ZenHub. I believe it does not add extra efforts.

**Comment by AntBush** [comment]
There's some additional validation that wouldn't be until onSave/on submitting, where we don't want to create an intake unless it doesn't overlap with another intake. That wouldn't be available until submitting when all the data is ready.

Comment on this: 
> Show next Intake number - auto calculated based on the dates that are entered. 
 
This may require a roundtrip from the DB (an "attempted save"), and isn't always feasible (if we have intake 3 and 4 already saved, and we make an intake between them, then we don't have a number in between to autocalculate)


Additionally: we can include the change of the grace period without growthbook (if we'd like to). 

@elliottSlee @MarsRomer since this comment is relevant to you

**Comment by elliottSlee** [comment]
fyi @AntBush, @eazeredo, @marcellmueller, @VB-at-Bis, @pdoc1111 
We are not doing the toggle visibility of dates anymore because this is controlled by growthbook. In lieu, we've added a line to the page description which is captured in #651 View Intake Dates.

- [ ] If "visible to applicant" is **unchecked** then next intake dates will not be visible within the applicant dashboard and landing page
- [ ] If "visible to applicant" is **checked** then next intake dates will be visible within the applicant dashboard and landing page
![Screen Shot 2023-01-18 at 4.54.21 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c6a54715-f761-49fa-b55c-903bfc3fbcfe)
#
![Screen Shot 2023-01-18 at 4.55.52 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8fd6ee54-3d25-41f3-a41d-f0967259d953)
#

**Comment by elliottSlee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1122?planning-poker) with Zenhub @rafasdc
