### ISSUE TITLE
Record Announcements

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1131]
As an analyst 
I want to track when projects are announced
So that I can manage past and future announcements better

# Acceptance Criteria:

## No announcements
- [ ] UI looks like screen design below when no announcements have been logged.
     - [ ] An announcement menu item exists below the Conditionally Approved accordion
     - [ ] When expanded the Primary and Secondary announcements show 'None' 
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/0503fa47-2716-4b4b-899e-68d92f2f27b5)

## Add announcement
- [ ] Click edit pencil then display div slides down out and form fields slide down in (e.g., https://codepen.io/seethroughtrees/pen/XbjoaJ) or use css transition 1s
- [ ] UI for when the edit pencil is clicked and no announcements have been logged yet 
- [ ] User can copy paste one URL into URL box - if more than one then don't allow them to save and provide feedback
- [ ] User can choose any date in past or future for announcement date
- [ ] Drop down should not show the current applications CCBC ID
- [ ] User can choose other CCBC IDs that was included in this announcement. Input field is a multiple value filter with chips, list of values is the CCBC Is (https://mui.com/material-ui/react-autocomplete/#multiple-values)
- [ ] If using Material UI input, ensure input box is the same height & border as other input boxes
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8a131cea-e073-4656-8e78-0e5b953e1df3)

- [ ] URL & date are required. Outlined in red if empty on save.
- [ ] Error message for incorrect URL appears below input field, "Invalid URL. Please copy & paste from your browser."
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/9bd3f847-e8b3-459c-8a49-1a9204a2f1fd)

- [ ] Success toast shows as screen design below on 'Save' action
- [ ] Success toast shows all the CCBC IDs
- [ ] If >3 CCBC IDs have been added, state the 3 CCBC IDs and "and more"
- [ ] Success toast slides in from left and appears at bottom left of viewport
- [ ] Success toast slides out to the left after 10s
- [ ] Click X on success toasts closes it
- [ ] Hover over CCBC ID of linked projects, tooltip opens saying "Opens a new tab" [example](https://www.w3.org/WAI/WCAG20/Techniques/working-examples/G201/new-window.html) | [code](https://www.w3.org/TR/WCAG20-TECHS/G201.html)
- [ ] Click on other CCBC IDs in the success toast will bring you to the announcement page for that project

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/40d9df00-0201-47a5-8ef0-53cb09cee670)

## List Announcements

**Screen**

- [ ] After 'Save' action, the UI shows a preview of the URL, announcement date, and CCBC IDs. 
- [ ] Up to 9 CCBC IDs show up in cols
- [ ] Order of CCBC IDs is ascending in cols
- [ ] if more than 9 CCBC IDs then 'and more' shows 
- [ ] After 'Save' action, the same UI shows for each CCBC ID that was selected. e.g., if you added CCBC 010005 as another project in this announcement, when you go to the announcement page for that project, the same announcement is available
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/5428ad2f-a51d-4463-8a89-b61e995167c2)
- [ ] Show changes to the announcement in the history table

## Delete Announcement
**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c921f43c-8ca0-49a7-a4fd-d38e5af176e7)
- [ ] Clicking red X beside an announcement opens the modal
- [ ] In the modal, clicking "Delete from all projects" removes the announcement from all projects that are linked including the current one
- [ ] In the modal, clicking "Remove from this project" will remove the announcement from the current project but it will remain for all other projects linked to it.
- [ ] In the modal, clicking "Cancel" or the X closes the modal with no changes made.
- [ ] The link previews are ordered chronologically with oldest at the top in each section (primary and secondary announcements)

## Not included
~- [ ] clicking on 'and more' shows all the CCBC IDs~

## Implementation Details
- **DB:**
  - [ ] two Boolean columns exist, one each for Primary Announcements, and Secondary Announcements exist and get populated with true if those types of announcements exist. This will make it easier to query in metabase.
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by elliottSlee** [comment]
#### Remaining questions to discuss
- [ ] (1) SHOULD WE HAVE THE DROP DOWN INCLUDE THE CCBCID of the current application
> I vote yes. If included, there doesn't need to be a custom way to remove the respective ccbc id from each page the announcement is displayed on.
- [ ] (2) Clicking on 'and more' shows all the CCBC IDs in some way (TBD). See 2 options in [this prototype](https://www.figma.com/proto/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?page-id=8776%3A39968&node-id=10831-97006&viewport=2619%2C13285%2C0.73&scaling=min-zoom&starting-point-node-id=10831%3A97006) by hovering over text or clicking the plus
- [ ] (3) A bigger question: Is this over-engineered for our user story? _As an analyst, I want to track when projects are announced so that I can manage past and future announcements better_ Tracking announcements is not nearly as important as $ and households. The basic need is date & url.
Things we may want to reconsider:
- We added the other projects feature to reduce amount of work but users even said they were fine without it before we showed it to them. 
- The link preview is pretty, but it's not truly needed. One analyst showed up a report for execs for which they open each link and copy the title. Perhaps we could redirect our effort to getting the titles through the same means as the link preview is pulling the title (e.g., `og:title`)

**Comment by VB-at-Bis** [comment]
my 2c: 
- (1) agree;
- (2) using + seems to be more in line with expand/collapse approach used in the app now;
- (3) 'other projects' feature is an easy win (imho), so it's not overengineering; 
- link preview could be an over-complication; getting the title is definitely less efforts (still may be error-prone as we have no control over target page content - i.e. `og:title` metatag may be missing, html `title` can be too broad and relate to the whole website etc.)

**Comment by AntBush** [comment]
1) I also agree, does this mean that the default behaviour should be to have auto-selected the current ccbc id then? I doubt we want the user to forget they've set the ID for the application they're currently on and it not appear after they save.
2) Agreed with Vlad
3) Are you asking about the announcements in general or just with the previewing? From my understanding, Mars wanted the previewing because it would act as a validation for the URL that was placed. I think a more iterative process where we just setup the skeleton (data in db and MVP display of that data) first and then prioritize the previews is the way to go, but I'm under the impression the previews are an important part of this feature - enough that it's worth doing them synchronously.

**Comment by MarsRomer** [comment]
1. I would be ok with the CCBC ID of the current application in the drop down if it's super clear that it's not available for selecting and that it's already selected.  Otherwise I can see a user getting thrown off by it.
2. I think the plus sign to expand and show all the CCBC ID would be great, possibly something we build down the road when it becomes obvious that they may actually have more than 9 projects listed
3. It's true we were considering it as a visual way to confirm that the url was legit.  However it's not super important.  Its a nice to have, but I think it will help overall in adding a friendly shine to the site.  I worry if we don't include it in this sprint, we may not get a chance to come back to add this shine later.

**Comment by elliottSlee** [comment]
@AntBush what are your thoughts on this link preview package? The design seems more flexible than the other one I had originally looked at. https://github.com/maherzaidoune/react-native-url-preview

**Comment by elliottSlee** [comment]
@AntBush what are your thoughts on this link preview package? The design seems more flexible than the other one I had originally looked at. https://github.com/maherzaidoune/react-native-url-preview

**Comment by AntBush** [comment]
Since this is a react-native package, I'm not sure if it's compatible with react in a browser environment (although it should be). The package hasn't been updated in 3 years, so the dependency of link-preview-js is also very out of date.

Rolling out our own with something like this: https://github.com/ospfranco/link-preview-js (dependency of the above package) could also be an option. We could maybe even work around the CORS issue if we render it on the server before passing the broken-down HTML elements back to the client. I'm not 100% sure though.

**Comment by eazeredo** [comment]
This card will be split into 4 subtasks, which are:

- Create/update announcement
- List announcements
- Delete announcement
- Show link preview

**Comment by MarsRomer** [comment]
Acceptance Criteria not met, but this is good enough for first iteration, these are minor issues that can be fixed once we get some user feedback.
1. if more than 9 CCBC IDs then 'and more' shows
2. The link previews are ordered chronologically with oldest at the top in each section (primary and secondary announcements)

**Comment by MarsRomer** [comment]
@marcellmueller @VB-at-Bis @AntBush @rafasdc I'm not sure which of you want to work on the bug above for this ticket but I'm putting this ticket in "in Progress'.  Please assign yourselves as you feel best

**Comment by marcellmueller** [comment]
looks like @rafasdc already has a fix for that issue here:

https://github.com/bcgov/CONN-CCBC-portal/pull/1675
