### ISSUE TITLE
Change text in Permitting Assessment

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1435]
As a permitting team member
I want the text in the flags to be updated
So that they reflect our work better

**Description:**
Permitting team wants a minor reword of text for the flags

# Acceptance Criteria:
- [ ] Wording for the flags follows the screen design below

## Permitting assessment

**Screen**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/bd24780b-d011-4050-8fa7-34e33358ec47)

### Not included:
- .
- .

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/1435?planning-poker) with Zenhub @AntBush @marcellmueller @VB-at-Bis

**Comment by AntBush** [comment]
@elliottSlee  @MarsRomer  With it being a checkbox, I'm noticing that these are mutually exclusive. Can it be "Normal permitting requirements and timelines anticipated" and "Major permit approval issues anticipated. Likely to influence timeline" at the same time? Same with the Minor as well.

**Comment by elliottSlee** [comment]
Unfortunately I cannot answer this today with the users on vacation. If you want to continue working on it, I believe there is less risk in the options remaining checkboxes than turning them into radio buttons.

**Comment by AntBush** [comment]
I mean I'm practically done with the work, just thought I'd ask while it was on my mind before I forgot haha

**Comment by AntBush** [comment]
@MarsRomer Gotcha! They're still checkboxes for now, but we'll need to find a way to migrate from this data if we want to in the future. Something I remembered now is that in the "Decision" section we put some shorthand for the flags. I'm wondering what should be there instead or if we want to keep the same nomenclature. 

The plan is to use the pills as is, the screenshot below has the text and the pills because I was messing around with the data but let me know if you'd like to change the text in these pills as well.
![image.png](https://images.zenhubusercontent.com/629114aa79d89c40669bc468/66dde7c0-f940-4eed-a731-6dd12c90018d)

**Comment by MarsRomer** [comment]
I just noticed a bug that may be related to this ticket.  The assessment page is erroneously showing flags that weren't check-off on the Permitting assessment tab.  
See below: No flags checked off
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/b56043c2-1e1b-4117-aa08-4437954f976d)
see below:
Assessment table shows that they were checked off
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/5f5fc270-8ac9-43e8-8fda-ac0fef3b930f)
 
Would you rather I open a new bug ticket, or move this ticket back to in-progress?

**Comment by AntBush** [comment]
This is just an artifact from there being old data, the old flags are being displayed there (note how it doesn't include the "Likely to influence timeline" on the major permit text). 

Since there is no old data in prod, we shouldn't see this issue but if you'd like I can whip up a script to clean the old flags out in test.

**Comment by MarsRomer** [comment]
thanks for looking into this @AntBush 
No need to fix this as you correctly note that there is no old data in prod
