### ISSUE TITLE
Create SoW data input UI

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#1544]
As an analyst
I want to upload the the Funding agreement, statement of work, and the final map
So that we can import all the important fields for a project and keep the important files together with the project in the Portal.

# Acceptance Criteria:

[**Wireframes**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=11373-105461&t=L5lghbAnIUdJZj0w-4)

## Empty state
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/818260db-8e33-4506-814c-868be73282ea)

![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/8a171858-f841-4d41-b92d-cec97b6c7617)

- [x] When radio button is `Yes` then other fields slide down (use same effect as in the announcements for consistency)
- [ ] `Funding Agreement signed by the both Recipient & Province` is required. File type is pdf or PDF
- [x] `statement of work tables` is required. File type is xls, xlsx, xlsm, XLS, XLSX, or XLSM
- [ ] Success toast appears
 ![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/5257fd14-c859-4fe2-9e8c-a6f538d4155d)

## Read-only page
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c7303f6e-08d1-4ebe-b026-9bf759c46a1d)
**Missing files**
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/5d27fbc9-7ba2-4458-8353-8781cd638f87)
- [x] Click file and it downloads
- [ ] customize the upload widget for the SOW xls upload to account for validation
- [x] Click edit pen (clickable area of 44px^2) and read-only slides out and form slides in similar to announcements form

### Not included:
 
Validation is going to be part of #1617

## Implementation Details
- **DB:**
  - .
  - .
- **Middleware:**
  - .
  - .
- **Frontend:**
  - .
  - .
- **Tests:**
  - .
  - .
- **Documentation:**
  - .
  - .

**Comment by marcellmueller** [comment]
We should be using SVG for logos whenever possible, I replaced the link to a PNG with an SVG I found on Metabase website https://www.metabase.com/images/logo.svg

**Comment by MarsRomer** [comment]
Looks great!  
Just a couple of notes:
1. Would it be possible to have the 'Date Funding Agreement Signed' box be narrow like the design and match the other date fields on this page?
2. Can the date be deleted with the little x like the other dates?
3. If the user picks a date and then chooses the 'Has the funding agreement been signed by the province?' radio button = 'No' and clicks save, then the date should clear out and not save.  This is currently not happening.  I know this because after saving when I come back and click 'Yes' radio button the date is pre filled instead of blank.
4.  Could we please reword  "Upload the completed statement of work tables" to "Upload the completed statement of work xls"

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee 

Okay I have a PR incoming taking care of issues 1 and 4 here, and will be working on the permanent datepicker clearing in ticket #1679 I created.

I created ticket #1680 `SoW Input UI - clear form data if 'No' is selected and saved` but it needs acceptance criteria added/refined before I can get started. If you are unsure we can always discuss it at standup tomorrow.
