### ISSUE TITLE
Bug: Login for analyst Prod redirects incorrectly

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1673]
**Describe the bug**
Analyst gets redirected to applicant login page

**To Reproduce**
1. Go to analyst prod
2. Enter idir and log in
3. . See error - redirects to login for applicant

**Expected behaviour**

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by rafasdc** [comment]
A bit more info for this ticket, there are two errors occurring: 
1. When someone logins an old token, likely from cache, is being used, which return in the 'token is not active' error, it has happened 11 times in the last 30 days of this comment. In the latest occurrence a token from end of day of August 9th was used on the user's first login on August 10th. 
2. The second occurs when state does not equal the cached state, this is likely due to a clock skew not matching between the OIDC server state and user's state. This might also occur if the user is using a bookmarked URL to directly login or clicking a browser that might have been opened for too long. Finally, this might be similar to 1 in which a cached state is being compared against a new state which would never match.

**Comment by rafasdc** [comment]
the first attempt at fixing this is up for review PR #2110 
Changes: 
- changes the authenticatd check to include a check of the presence of the refresh token as well as checking if the session token set is not expired. **Note:** we might have to adjust this logic further as currently the expired check will check if the *access token* is active as that is the default check of the token set, we might need to write further logic to check if the *refresh token* is expired.
- Changed the login and auth call back to not attempt to check the state twice and leave it up to the openid-client library, added further captures of the session and query if there is a failure in the auth callback.

We might also want to consider truncating the `ccbc_private.connect_session` table. 

Further steps if this is not resolved:
- Add check for refresh token
- Reduce cookie to 8 hours; or keep cookie in sync with refresh token (30 minutes)
- Upgrade openid-client and express-session

**Comment by rafasdc** [comment]
The logic has been changed to check if the refresh token is expired instead of the default expired method.

Note that the token set controller does not have an else for when the use is not authenticated and somehow got to it, we might have to add one to delete the session if this occurs often.

**Comment by MarsRomer** [comment]
Bug:  Logout does not work.  In regular mode on chrome it logs me in without the IDIR sign in after I have logged out
