### ISSUE TITLE
Tech Debt - Discover which id's to use in database session function

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#169]
We need to research on how to capture the following Id's for logging in users: `Github, IDIRs, BCeID basic, BCeID business`

Then add these ID's to the `session.sql` function to allow the correct type of logged in users. Currently we just will accept any `JWT` but should reduce that down to only the IDP we want to allow.

This ticket also includes implementing the capturing of the ID from the upstream provider.

**Comment by MarsRomer** [comment]
@marcellmueller  would you mind taking a look at this ticket to see if we still need it please?

**Comment by VB-at-Bis** [comment]
Added new field `identity_provider` to types/keycloak_jwt. Now it will contain one of the following: `github`, `idir`,`bceid-basic`, `bceid-business`. As an identifier, Junmin strongly suggested to use `preferred_username` because that's what is used by Keycloak as `keycloak_username`.
Attached is IDP mapping :
![image.png](https://images.zenhubusercontent.com/621d06da1613ac1631e8f9b6/dbe70360-bf3a-44f1-ba65-b902e95d95ee(from https://user-images.githubusercontent.com/56739669/172924027-891f22c4-4d6b-48a1-bf41-54babf0d87a9.png))

**Comment by VB-at-Bis** [comment]
PR submitted:
Keycloak is using `preferredUsername` as unique user identifier `keycloak_username`.
Code changes:
- added identity_provider in keycloak_jwt type
- updated code to populate identity_provider from JWT
- updated revert action for applications table that was blocking sqitch revert and sqitch deploy

**Comment by MarsRomer** [comment]
@VB-at-Bis  is there some way I can review this?

**Comment by VB-at-Bis** [comment]
I was using local Graphiql to check what's in session:
![image](https://user-images.githubusercontent.com/100612619/183092281-f5ddabd1-462c-4467-84c0-a1ed5173ed07.png)
I'll check if it can be verified in metabase. Code was merged and deployed to dev/test, so hopefully, Metabase has data
