### ISSUE TITLE
Bug: Timeout occurs even when actively using

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1690]
**Describe the bug**
Sometimes even when the user is using the application, the timeout modal pops up.  Time out modal counts down from a big number instead of 2 minutes.

**To Reproduce**
1. Work in prod for several minutes
2. see modal for timeout
3. Modal should count down from 2 minutes

**Expected behavior**
Modal only shows up after 20 min of inactivity, and count down from 2 minutes

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by rafasdc** [comment]
Since this relies on the Keycloak refresh token the maximum session is 30 minutes.

After the fix, the inactivity modal will ONLY show when there are two minutes left in the token/session and will count down from ~120 seconds, this will happen AFTER 28 minutes of inactivity, we can make it 20 minutes but that means the counter will count down from 600. 

Also, making it so activity is detected every 1 minute up from 3.3minutes, activity is any keystroke, scroll, mouse click, or page navigation. 

The inactivity modal will really only show when the user stays static on one specific page.
