### ISSUE TITLE
Bug:  Image on link preview is distorted

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1727]
**Describe the bug**
Images in the link preview of announcements are not keeping their aspect ratio and look distorted

**To Reproduce**
1. Go to Project page
2. add announcements with these links
3. Save
4. See images distorted

**Expected behaviour**
Regardless of what happens on the link preview page, the images should not be distorted.  
**use Object - fit : contain**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63c8370399512153492c8e97/20e165ff-bbd9-4a4f-9a10-7ff34f03178b)If applicable, add screenshots to help explain your problem.

**Logs/tracebacks**

**Additional context**

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee 

After looking into this there isn't a perfect solution for images of varying aspect ratios. I tested with two URLs:
https://news.gov.bc.ca/releases/2023CITZ0010-000652
https://news.gov.bc.ca/releases/2018CITZ0005-000389

Current squished view for both:
![original](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/ca0ed56f-9a59-4b80-8d9f-104cf8396e8d)
![original-2](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/5d106136-52a4-47b8-a429-142969db0338)


Option 1 using `object-fit: cover` which will cut some of the image off to maintain aspect ratio. It works well for the second image with the logo since the logo is centered but looks strange for the first image.

![object-fit-cover](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/042efd28-e191-471e-8762-94d4fbaab222)
![object-fit-cover-2](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/c594db12-1c4c-4788-bb16-7a534733e89c)

Option 2 using `object-fit: contain` which will maintain the aspect ratio but keep the image in the frame:
![object-fit-contain](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/b2663b84-3649-4036-8090-1b0a3235eb0f)
![object-fit-contain-2](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/8d6b5529-8d17-483e-b6ae-a696dd45ac28)

Let me know which you prefer or if you have any other ideas!

**Comment by elliottSlee** [comment]
I prefer `object-fit: cover`

**Comment by MarsRomer** [comment]
I like the second option, it's good to be able to see the whole image.  Cutting the image off on the sides makes it look buggy

**Comment by marcellmueller** [comment]
Two different answers 😅 

Can someone update the acceptance criteria and I will finish this ticket, if not we can discuss at standup tomorrow. Thanks 🙂

**Comment by elliottSlee** [comment]
PO trumps all

**Comment by marcellmueller** [comment]
Sounds good, this will keep the full image for wider ones and the square ones on the federal government pages:
![Screenshot 2023-06-29 at 2 55 24 PM](https://github.com/bcgov/CONN-CCBC-portal/assets/14259474/ce1feca6-6161-424f-bd27-eda3df82f6ab)

**Comment by MarsRomer** [comment]
Object fit Contain it is, I've updated the ticket

**Comment by marcellmueller** [comment]
Done 😄
