### ISSUE TITLE
spike:  Make radio buttons agile

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1775]
Radio button changes take a lot of effort.  This ticket it is to make it easier.

Changes such as changing the label or adding and removing radio buttons should require minimal effort.

**Comment by marcellmueller** [comment]
@MarsRomer @elliottSlee 

I think we need to consider about what we are actually trying to achieve here. We want to be able to change the text of the radio option while still keeping the option selected in a form that was already saved.

To me it seems like that is okay if we only modify the spelling/wording, not change the entire meaning of the question. It doesn't make sense to completely change the meaning then have people's name saved in the history attached to these decisions. It's has the potential to be very misleading going forward.

Given that I am going to propose that we can only change the label if the intent of the original selection is the same. We can do that with a `ui:option` named `enumRename` or `enumLabels` (enum values is what the options are called). This would override what is displayed as the label but the value would stay the same as the original, keeping it selected and hopefully still clear as to what the answer was on metabase.

It might be an edge case a selection is supposed to change so much that it wouldn't make sense with the original value then I think we need to make a completely new selection, delete the old one and accept that any ones that were checked would not be checked anymore. Since it wouldn't be right to put someone's name on something they did not select.

Let me know if that makes sense to you or you have any other comments.

**Comment by MarsRomer** [comment]
Hey @marcellmueller  yes it all makes sense, the intention was never to change the meaning of the radio button, but sometimes we need to change the wording to be more in line with the business process or for clarification.  If we end up needed to remove and option and add an option, that would not be done with a label change of an existing radio button.  It seems like your idea of the enum values that you have laid out above would be sufficient for this scenario

**Comment by marcellmueller** [comment]
Sounds good, would you like me to add this feature to the radio buttons as part of this ticket? I don't think it would take very long.
