### ISSUE TITLE
SoW upload bugs

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1838]
**Describe the bug**
Sometimes the SoW upload seems to work but doesn't actually upload.  At other times it works fine.  Sometimes the SoW should have thrown validation errors but it doesn't.
 This ticket is to investigate and fix any sentry errors due to this bug and look for any other obvious reasons why there could be a problem.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by marcellmueller** [comment]
@MarsRomer fixing this is blocked by the loading spinner ticket #1839. The reason this seems like it doesn't work is because there is no user feedback while the SoW validates and saves the data unlike the SoW widget which has the `validating data...` animation and loading spinner.

Let me know if that ticket is good and I will implement it. It currently says needs refinement, I think the designs just need to be finalized.

**Comment by MarsRomer** [comment]
ok if there is no bug we can close this ticket, thanks @marcellmueller
