### ISSUE TITLE
Crashing Pods

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#1871]
**Describe the bug**
Pods are crashing and sysdig is sending notifications.  This ticket is to investigate and if the fix is low effort, fix it.  If the fix is medium or high effort, create tickets for fix.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Logs/tracebacks**

**Additional context**

**Comment by marcellmueller** [comment]
This seems to have been a database pod with crashing `pgbackrest` container due to OOM (out if memory) crash. We investigated it but were unable to find the cause so we reset it with `patronictl reinit` and then also completely killed the pod and restarted it. 

We then manual ran the `pgbackrest` cronjobs and there were no issues, as well as checking on it today everything seems in order again. We will continue to monitor this and ensure it doesn't come up again and if so maybe try giving the container a little bit more cpu and memory.
