### ISSUE TITLE
pgBackRest container CPU throttling

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/CONN-CCBC-portal#2269]
`pgBackRest` containers are causing frequent sysdig  notifications `Prod - Container CPU Throttling is Triggered`. We should investigate why this is happening and adjust resources accordingly.

**Comment by rafasdc** [comment]
There is no actual throttling happening here. Nevertheless, the Prometheus query needs to be adjusted, currently is is using the sum percentage of a cpu on a *container* which is leading to this fall positive. The pod itself is way below the throttle level but since pgbackrest container inside the pod is running the backups it is going to 400% + of usage for its container (50m) which is then triggering this false positive. 

The query needs to be adjusted to calculate the total cpu *pod* usage in divided by the *pod* limit.

**Comment by rafasdc** [comment]
Prometheus query has been adjusted.
