### ISSUE TITLE
Increase Logout Time

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2294]
As an analyst 
I want to stay logged in for a long time
So that I can continue to work on the assessment without interruption

**Description:**
This is for increasing the time for logout to 8 hours

# Acceptance Criteria:
- [ ] Analyst is not logged out for a longer period of time (TBD)

Note:  Depends on the max time that the SSO team allows for token refresh

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2294?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by elliottSlee** [comment]
A suggestion is to check authentication every 24 hours in the background. Thus, if they have for some reason or another, already authenticated within the past 24 hours, it may just look like it's taking a few seconds longer to load but is actually running through the steps of going to keycloak.
Alternatively, set sessions to expire at a particular time of day (e.g., midnight) instead of after a duration because if someone logs in at 11:00am their first time then visits the next day at 10 they won't be asked to sign in, but while working at 11, they'll be asked to login again.

**Comment by rafasdc** [comment]
From SSO team: "... there is no set limit; it just depends on what your team is looking for and if it passes your STRA.."
