### ISSUE TITLE
Spike: Assessment Assignment table Filtering Refinement

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2460]
Description:
Filtering on the assessment assignment table is not intuitive, this ticket is to explore how the filtering works and suggest improvements.

AC:
- [x] Review how filtering is working when typing and make recommendations for improvement in separate ticket(s)
- [ ] Adjust columns to allow all filters to be justified at the top (alternately see if there is a way for user to adjust column widths)

![image](https://github.com/bcgov/CONN-CCBC-portal/assets/120044407/1afa4bac-1e19-4a50-9913-f90963154074)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2460?planning-poker) with Zenhub @AntBush @rafasdc

**Comment by marcellmueller** [comment]
@MarsRomer I ended up fixing the sorting/filtering issues in this spike as I was trying to figure out what the issue was and making sure we could fix it and was half way there.

- The CCBC ID column filtering will not return any value that contains an 01 anymore if you type say ccbc-01, it will return all values that start with ccbc-01.
- All four assessment columns sorting and filtering is fixed. This was due to the value being an object since it has the custom dropdown for editing so by default the sorting/filtering was broken as it didn't know which values to look for.

Also, you weren't at standup today but I didn't fix the column issue as Elliott said we are removing the word 'Assessment` for the column headers in another ticket that will solve the issue.
