### ISSUE TITLE
Star not showing beside the latest file received

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2606]

**Comment by rafasdc** [comment]
The logic for the star showing is: 

- If the field does not allow multiple files (single file only)
- AND, it's the first file on the list (the latest file)
- THEN, show star

One thing to note, on the RFI upload page all uploads are multiple, so if the applicant uploaded one file first but didn't remove it and then uploaded the second one the field will be "multiple" so the star will not show.

**Comment by MarsRomer** [comment]
Thanks @rafasdc  
I wonder if we should change the criteria and logic for the star display.  Ideally we want the star to work on the fields that are displaying as single file uploads in the application forms, regardless of what happened during RFI.  So that would be all of the templates, and the KMZ file and the Coverage Statistics XML file.  Perhaps we could hard code that logic?

**Comment by rafasdc** [comment]
@AayushAnand007 what was the application that was having this issue?

**Comment by AayushAnand007** [comment]
@rafasdc CCBC-010030

**Comment by rafasdc** [comment]
I've gone through the data for this and the issue is around our logic. Currently we only show the star on the **latest RFI**, meaning that if a type of file was not requested through the RFI it will not show the star. In this scenario the latest file for template 2 is, according to our logic, properly not showing the star since it was not requested and/or uploaded as part of RFI 13. Nevertheless, the file was requested as part of RFI 12. 

We would have to update the logic to be file/request based instead of RFI based. So instead of showing the stars only for the latest RFIs (this is likely assuming that the same type of files will always be requested), we show the starts for the latest type of file/request no matter which RFI it was uploaded (it should always show start on the newest file uploaded via RFI). 

We'll likely need to discuss this a bit more during standup.

**Comment by MarsRomer** [comment]
thanks @rafasdc lets discuss this at our stand up tomorrow
