### ISSUE TITLE
Bug: Inactivity modal pops up while active

### ISSUE THREAD

**Issue by MarsRomer-zz** [bcgov/CONN-CCBC-portal#573]
This has been reported by one of the NWBC testers and replicated by me:
The inactivity modal popped up after approx 30 min of continual use of the application portal.  I was not inactive for more than a couple of minutes.
Also of note that the countdown is still more than 2 min long which isn't a high priority fix.

![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/6a34dfb0-c94a-4d25-86cf-9712e96530d6)

A few days later, in test environment the modal popped up but the counter was already at 0 seconds
![image.png](https://images.zenhubusercontent.com/62686bda7385b9a511da26e2/14cfe5d9-5371-45e4-af01-21d3525ce81f)

**Comment by AntBush** [comment]
@matthieu-foucault mentioned at one point that a setting on the SSO app was changed that is likely to resolve this issue (unless I'm misremembering), is there an update we can add to this?

**Comment by matthieu-foucault** [comment]
There is, thanks for the reminder. The Gold cluster realm had a setting that enforced single use of refresh tokens. 

That setting was causing issues with our session extension (i.e. asking for a new access/refresh token to take the session past 30min) on a race condition: if a session extension was attempted on a page load or any other action that caused multiple requests to be handled concurrently, the second request would fail, because it's refresh token would have been used by the first request.

After discussion with the SSO team, this setting has now been disabled.
I would:
- wait until this bug can be reproduced again before confirming whether any work is needed on this.
- open an issue in the https://github.com/bcgov/cas-template-app/, where the `sso-express` package is currently located, explaining that it doesn't support single use refresh tokens.

**Comment by MarsRomer** [comment]
I will test it out to see if the bug still exists... will know shortly
