### ISSUE TITLE
Analyst Dashboard - Filters

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/CONN-CCBC-portal#647]
## User Story
As an analyst, 
I want to filter applications
so that I can easily find them

### Filter fields
| Field         | Type     | Domain                       | MaxLength |
|---------------|----------|------------------------------|-----------|
| CCBC ID       | text     | -                            | 6         |
| Status        | Dropdown | List of implemented statuses | -         |
| Project name  | Text     | -                            | 60        |
| Oraganization | Text     | -                            | 60        |
| Lead          | Dropdown | Full list of analysts        | -         |
| Package       | Dropdown | List of existent packages    | -         |

### Page behaviour
**Filter by button**
Filter icon: https://fontawesome.com/icons/filter?s=solid&f=classic
Icon & text colour: #3F5986
Button colour: #3F5986 16%

- [ ] **Show filter row (1st click):** 
Given the filter row is hidden
When I click on the "Filter by" button
Then the filter row slides **down** `css {transition: all .5s ease-in-out;}`
And the filter by button changes to selected (`#3F5986 50%`)
#
- [ ] **Hide filter row (2nd click):** 
Given the filter row is visible
When I click on the "Filter by" button
Then the filter row slides **up** `css {transition: all .5s ease-in-out;}`
And the filter by button changes back to (`#3F5986 16%`)
And the applied filters are reseted
#
**Filter Behaviour**
- [ ] Show "Number of results" after a filter is applied
- [ ] Sort order is kept when filters are applied
- [ ] For text input filters, begins after 3 characters typed and 500ms delay
- [ ] For text input filters, typing another character, the filter will search for all the letters together anywhere in the results
- [ ] For text input filters, a "space" character has the same behaviour as any other character
- [ ] For text input filters, backspacing to no characters removes the filter (and chip)
- [ ] For dropdown filters, selecting an empty value removes the filter (and chip)
- [ ] Filtering by two or more fields, they will be combined by an inclusive clause (status="Received" AND organization="TELU")
- [ ] If filter & sort are applied, "clear filtering" is on the left and "clear sorting" is on the right
#
**Chip**
- [ ] Chip appears above the table when a filter is applied
- [ ] Remove the filter by clicking x on the chip
- [ ] CCBC ID chip says "ID"
- [ ] Project title chip says "Title"
- [ ] Organization chip says "Org"
- [ ] Status, Lead, & Package are not abbreviated
- [ ] width of chip is auto-sized to hug contents up to max width 286px, after which text is truncated
- [ ] Chips continue to second line if there is not enough screen width. Second line left-margin is in line with the first chip (ie. _not_ beneath the filter by button)
#

## Design
[**Default view**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9635%3A55319&t=s4cWFIdgcq4mH089-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/006fd247-ff72-4cff-a836-5570365531f1)
#
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/d2b6a31f-1eb8-427d-b8d5-d1715f25102f)
#
[**Filtered Example**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9635%3A55443&t=s4cWFIdgcq4mH089-4)
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/a97a58e3-3081-41a1-a2aa-5f2ab085bae2)
#
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/7df1f9b2-1263-4d5d-ad97-0b679eb21112)
#
[**Chips**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?node-id=9634%3A55081&t=s4cWFIdgcq4mH089-4)

<img src="https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/048ffdc5-9bbf-4f8b-804b-9fca2d7da805" width=70%>

Technical requirement:
- Will need to ensure that the connection is being reused rather than a new connection being made anytime a filter is being changed

**Comment by zoeyli-46** [comment]
@elliottSlee thoughts on the and/or logic for each of them? they are a bit wonky

**Comment by elliottSlee** [comment]
Blocked by design decisions of eligibility assessment outcomes

**Comment by zoeyli-46** [comment]
Is this now unblocked given that we have the outcomes

**Comment by AntBush** [comment]
Looking into the CAS table, it looks like we'd have to use this extension: https://github.com/graphile-contrib/postgraphile-plugin-connection-filter to include filters on the table. There are some other settings we'd want to look into for this, and also will need to some checks on load testing to see if we need to create any indexes on the `jsonb` columns and their nested fields to increase speed. There are some tradeoffs to this that we'll need to examine with some additional load testing and analyses.

**Comment by MarsRomer2** [comment]
I noticed that it doesn't do dynamic filtering, i.e. you have to click Apply after you have typed in the filter.  Would it be a setting to allow dynamic filtering or does it require more custom coding?

**Comment by eazeredo** [comment]
@elliottSlee and @zoeyli-46 , the wireframes links are pointing to hidden frames. 
Can you add the screenshot on the card?

**Comment by elliottSlee** [comment]
@eazeredo as mentioned yesterday, these cards are outdated. We will be starting them over from scratch when we have more solidified designs. In chat with Mars, we decided that we need to figure out more about dev effort for different aspects.

**Comment by elliottSlee** [comment]
@MarsRomer2 AC & wireframes updated for this card

**Comment by eazeredo** [comment]
@elliottSlee , follow some suggestions below for the first part. 
I also added a few new ACs.
#
## User Story
As an analyst, 
I want to filter applications
so that I can easily find them

## Acceptance Criteria
### Filter fields
| Field         | Type     | Domain                       | MaxLength |
|---------------|----------|------------------------------|-----------|
| CCBC ID       | text     | -                            | 6         |
| Status        | Dropdown | List of implemented statuses | -         |
| Project name  | Text     | -                            | 60        |
| Oraganization | Text     | -                            | 60        |
| Lead          | Dropdown | Full list of analysts        | -         |
| Package       | Dropdown | List of existent packages    | -         |

### Page behaviour
**Filter by button**
Filter icon: https://fontawesome.com/icons/filter?s=solid&f=classic
- [ ] **Show filter row (1st click):** 
Given the filter row is hidden
When I click on the "Filter by" button
Then the filter row slides **down** `css {transition: all .5s ease-in-out;}`
And the filter by button changes to selected (`#3F5986 50%`)
#
- [ ] **Hide filter row (2nd click):** 
Given the filter row is visible
When I click on the "Filter by" button
Then the filter row slides **up** `css {transition: all .5s ease-in-out;}`
And the filter by button changes back to (`#3F5986 16%`)
And the applied filters are reseted
#
**Filter Behaviour**
- [ ] Show "Number of results" after a filter is applied
- [ ] Sort order is kept when filters are applied
- [ ] For text input filters, begins after 3 characters typed and 500ms delay
- [ ] For text input filters, typing another character, the filter will search for all the letters together anywhere in the results
- [ ] For text input filters, a "space" character has the behaviour of an "OR" for the field (organization="TELUS" OR "Rogers")
- [ ] For text input filters, backspacing to no characters removes the filter (and chip)
- [ ] For dropdown filters, selecting an empty value removes the filter (and chip)
- [ ] Filtering by two or more fields, they will be combined by an inclusive clause (status="Received" AND organization="TELU")
#
**Chip**
- [ ] Chip appears above the table when a filter is applied
- [ ] Remove the filter by clicking x on the chip
#

**Comment by elliottSlee** [comment]
@eazeredo Looks much more legible, go ahead & put that in the card. Except please remove this AC: > For text input filters, a "space" character has the behaviour of an "OR" for the field (organization="TELUS" OR "Rogers")

**Comment by eazeredo** [comment]
@elliottSlee I changed it from
> For text input filters, a "space" character has the behaviour of an "OR" for the field (organization="TELUS" OR "Rogers")

to

> For text input filters, a "space" character has the same behaviour as any other character

I think it's important to make clear the expected behaviour of the space character.
