### ISSUE TITLE
Discussion Analyst Role And Permission

### ISSUE THREAD

**Issue by AntBush** [bcgov/CONN-CCBC-portal#662]
The purpose of this ticket is to find out what permissions an analyst should have, as well as if there are different kind of analyst roles. 

The questions to answer for this ticket are: 
1. How many analyst roles are there?
- Admin
- Analyst
- Reviewer
- Reporting
- Developer

2. What are the CRUD permissions of these roles?
- https://miro.com/app/board/uXjVOnpFeNI=/?moveToWidget=3458764536158694533&cot=14

![Screen Shot 2022-10-19 at 12.26.37 PM.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/c8b4ae8b-1229-44f2-8924-871e313573a4)

## Technical Details

- [ ] .
- [ ] .
- [ ] .

**Comment by elliottSlee** [comment]
At time of writing, this could change:
1. There are two analyst roles (a third with limited access to metabase will become necessary later on): analyst and admin (third will be comms)
2.
```
           |___________Table____________
            |  Application  |  Intake  |
_Role___________________________________
Analyst     |  CR           |  R       |
Admin       |  CR           |  CRUD    |  
Comms       |  R?           |  R?      | 
```
Delete shouldn't be necessary for applications since we have a withdraw function and analysts will be able to set status as closed, but please correct me if you think it is.
CRUD permissions depend on how we're treating edits. If edits mean creating a new record, so that we can handle multiple versions of the applications, then analysts would have CR. If edits mean that a single record is edited while somehow tracking changes, then they would need U as well.
Comms will only have Read permissions; likely through metabase. They can only see a few fields of applications that are past conditionally approved status, nothing in previous statuses.

**Comment by zoeyli-46** [comment]
In the future there may be Financial people too, they'll likely be just Read (same as Comms), though we'd imagine they don't need to see the Application or History tabs

**Comment by MarsRomer** [comment]
This needs to be a meeting.
