### ISSUE TITLE
Nav bar and Footer < #30

### ISSUE THREAD

**Issue by BryanGK** [bcgov/CONN-CCBC-portal#75]
Our application should be branded with a BCGov nav bar and footer, with the appropriate links, log out button.

- [x] import BCgov nav bar
- [x] implement navbar in the correct location
- [x] determine appropriate links in navbar and footer
- [x] import bcgov footer
- [x] implement footer in the correct location

**Comment by BryanGK** [comment]
@zoeyli-46 @elliottSlee Are you able to determine the appropriate links to be placed in the navbar and footer? Thanks

**Comment by elliottSlee** [comment]
Sorry we haven't filled this out yet. It's part of our user story mapping that we began yesterday. Here's what I have so far:

### User Story
As an Applicant I want to see a navbar that contains a help link, so that I can get help if I need it.

### Acceptance Criteria
Given that a user is on any page, when they click on the help link, their mail client opens with an email to connectingcommunitiesbc@gov.bc.ca


### User Story
As an Applicant I want to see a footer with links to Home, Disclaimer, Privacy, Accessibility, and Copyright , so that I know where I can find pertinent information and that I see familiar things within the BC Design System

### Acceptance Criteria
Given that a user is on any page of the application, when they click on Home, then they are redirected to the dashboard of the form.
Given that a user is on any page of the application, when they click on Disclaimer, Privacy, Accessibility, and Copyright, then a new tab opens with these pages 

Disclaimer: https://www2.gov.bc.ca/gov/content/home/disclaimer
Privacy: https://www2.gov.bc.ca/gov/content/home/privacy
Accessibility: https://www2.gov.bc.ca/gov/content/home/accessible-government
Copyright: https://www2.gov.bc.ca/gov/content/home/copyright

**Comment by BryanGK** [comment]
Navbar and footer implemented with PR #109 

@MarsRomer can you please review and OK the navbar and footer? 
https://ccbc-dev.apps.silver.devops.gov.bc.ca/

**Comment by MarsRomer** [comment]
@BryanGK  the header and footers look awesome!  Thanks!  We can consider this ticket/card as done. :)
