### ISSUE TITLE
Write view for Metabase use

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#771]
As an analyst 
I want to be able to see all the form data in one table (view) 
so that it is easy to query and I don't need to update my queries when there are changes to the database

### Acceptance Criteria

-  [x] All form data is available in metabase, with each form field parsed out in separated columns
 - [x] View should return the name of uploaded fields
-  [x] view should show current application status
- [x] only show applications that do not have 'Draft' status (i.e. has `submitted` in its `application_status` records)
- [x] view is tested

Note:  Ali has already written scripts to parse the data into separate columns so please connect with him if you need to use his work.

**Comment by matthieu-foucault** [comment]
> only show applications that have 'Received' status

@MarsRomer , I thought we had discussed using metabase for filtering instead. Did you forget to update the acceptance criteria?

**Comment by VB-at-Bis** [comment]
Talked to Ali. Example of the report - https://ccbc-metabase-test.apps.silver.devops.gov.bc.ca/question/77-parsedformdata-oct13

**Comment by MarsRomer** [comment]
hey @VB-at-Bis what is the name of the view?  Im looking for it in Metabase

**Comment by VB-at-Bis** [comment]
> 

summary_view :)

**Comment by VB-at-Bis** [comment]
Was it deployed to test? I created question in Metabase https://ccbc-metabase-test.apps.silver.devops.gov.bc.ca/question/81-summary-view but it fails to load ..

**Comment by VB-at-Bis** [comment]
View did not work as expected due to Postgresql rule that `Access to tables referenced in the view is determined by permissions of the view owner`. View is created under `ccbc` user. Changing the owner of the view or changing permissions of the `ccbc` user to bypass RLS would mean opening security hole and effectively disabling row-level security.

Thus, alternative approach was implemented (using Metabase Model) - see https://ccbc-metabase.apps.silver.devops.gov.bc.ca/model/36-all-application-data 
Using Model provides same user experience as using Table or View (foreign key relationships, filters etc.)

P.S. ticket https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/828 was created to remove unneeded `summary_view` code.

**Comment by MarsRomer** [comment]
hey @VB-at-Bis  thank you for this, is it possible to add the column that holds the 'state' of the application, i.e. Submitted, Draft etc?  I don't think I see it in this model

**Comment by VB-at-Bis** [comment]
I updated the model to include application status. https://ccbc-metabase.apps.silver.devops.gov.bc.ca/model/36-all-application-data
